
/* ACF */

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_%eb%a7%a4%eb%ac%bc%ec%a0%95%eb%b3%b4%eb%93%b1%eb%a1%9d',
		'title' => '매물정보등록',
		'fields' => array (
			array (
				'key' => 'field_55f3100c317b8',
				'label' => '거래상태',
				'name' => 'house_situation',
				'type' => 'radio',
				'instructions' => '<p>등록한 매물의 거래 성사 후 방문자들의 편의를 위해서 <span style="color:red">거래완료</span>로 변경하세요.</p>',
				'required' => 1,
				'choices' => array (
					'거래중' => '거래중',
					'거래완료' => '거래완료',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_55f311dd68957',
				'label' => '등록안내',
				'name' => '',
				'type' => 'message',
				'message' => '<p style="color:green">*** 전화번호는 회원 정보 페이지에서 등록할 수 있습니다. 한 번만 등록하면 매물 등록 시 신경쓰지 않아도 됩니다. 이미 등록했다면 무시하세요. ***</p>
	<p><a href="/wp-admin/profile.php" target="_blank">전화번호 등록하기</a></p>
	<p style="color:blue">*** 다음의 3가지 탭에 매물의 정보를 등록해야 합니다. ***</p>',
			),
			array (
				'key' => 'field_55f3124155640',
				'label' => '기본정보',
				'name' => '',
				'type' => 'tab',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55f3100c317b8',
							'operator' => '==',
							'value' => '거래중',
						),
					),
					'allorany' => 'all',
				),
			),
			array (
				'key' => 'field_55f3129995993',
				'label' => '등록구분',
				'name' => 'house_agent',
				'type' => 'radio',
				'required' => 1,
				'choices' => array (
					'직거래' => '직거래',
					'중개거래' => '중개거래',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_55f3132119c87',
				'label' => '매물구분',
				'name' => 'house_type',
				'type' => 'radio',
				'required' => 1,
				'choices' => array (
					'주택' => '주택',
					'아파트' => '아파트',
					'오피스텔' => '오피스텔',
					'상가' => '상가',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_55f3137c09421',
				'label' => '거래구분',
				'name' => 'house_part',
				'type' => 'radio',
				'required' => 1,
				'choices' => array (
					'월세' => '월세',
					'전세' => '전세',
					'매매' => '매매',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_55f313e5b7db3',
				'label' => '거래금액',
				'name' => 'house_price',
				'type' => 'number',
				'instructions' => '<p>\'매매\'의 경우 전체 금액을, \'전세\' 또는 \'월세\'의 경우는 전세 보증금 또는 월세 보증금을 입력하세요.</p>
	<p>(예) 5백만원이면, \'<span style="color:red">500</span>\' 숫자만 입력합니다.</p>',
				'required' => 1,
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_55f31574b9160',
				'label' => '월세',
				'name' => 'house_mprice',
				'type' => 'number',
				'instructions' => '<p>\'전세\' 또는 \'월세\'의 경우에만 입력하세요. 월세가 없다면 \'<span style="color:blue">0</span>\'을 입력하세요.</p>
	<p>(예) 5십만원이면, \'<span style="color:red">50</span>\' 숫자만 입력합니다.</p>',
				'required' => 1,
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_55f315eb0f435',
				'label' => '관리비',
				'name' => 'house_fee',
				'type' => 'number',
				'instructions' => '<p>관리비가 없다면 \'<span style="color:blue">0</span>\'을 입력하세요.</p>
	<p>(예) 5만원이면, \'<span style="color:red">5</span>\' 숫자만 입력합니다.</p>',
				'required' => 1,
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_55f3165fb735b',
				'label' => '관리비내역',
				'name' => 'house_item',
				'type' => 'text',
				'instructions' => '<p>관리비에 포함된 항목을 간단히 입력하세요.</p>
	<p>(예) <span style="color:brown">인터넷, 계단청소, 엘리베이터 사용료</span></p>',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55f316a70eba0',
				'label' => '부가정보',
				'name' => '',
				'type' => 'tab',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55f3100c317b8',
							'operator' => '==',
							'value' => '거래중',
						),
					),
					'allorany' => 'all',
				),
			),
			array (
				'key' => 'field_55f316d8125a2',
				'label' => '층',
				'name' => 'house_floor',
				'type' => 'number',
				'instructions' => '<p style="color:red">지하 층은 등록할 수 없습니다.</p>',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '1 ~ 100 사이의 값',
				'prepend' => '지상',
				'append' => '층',
				'min' => 1,
				'max' => 100,
				'step' => '',
			),
			array (
				'key' => 'field_55f317216de3e',
				'label' => '방',
				'name' => 'house_room',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '1 ~ 50 사이의 값',
				'prepend' => '방',
				'append' => '칸',
				'min' => 1,
				'max' => 50,
				'step' => '',
			),
			array (
				'key' => 'field_55f31775ae761',
				'label' => '빌트인',
				'name' => 'house_builtin',
				'type' => 'checkbox',
				'choices' => array (
					'냉장고' => '냉장고',
					'선풍기' => '선풍기',
					'에어컨' => '에어컨',
					'세탁기' => '세탁기',
					'신발장' => '신발장',
					'싱크대' => '싱크대',
					'옷장' => '옷장',
					'침대' => '침대',
					'TV' => 'TV',
				),
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_55f318110b131',
				'label' => '주차, 승강기',
				'name' => 'house_park_elv',
				'type' => 'checkbox',
				'required' => 1,
				'choices' => array (
					'주차' => '주차',
					'승강기' => '승강기',
				),
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_55f318b03b093',
				'label' => '입주 가능일',
				'name' => 'house_movedate',
				'type' => 'date_picker',
				'instructions' => '<p>입력한 <span style="color:red">날짜 이후부터</span> 입주 가능함을 의미합니다.</p>',
				'required' => 1,
				'date_format' => 'yy-mm-dd',
				'display_format' => 'yy-mm-dd',
				'first_day' => 0,
			),
			array (
				'key' => 'field_55f318e92ad83',
				'label' => '비고',
				'name' => 'house_comment',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '매물에 대한 추가 정보를 자유롭고 간단하게 입력하세요.',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_55f3191888cdb',
				'label' => '위치정보 및 사진',
				'name' => '',
				'type' => 'tab',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55f3100c317b8',
							'operator' => '==',
							'value' => '거래중',
						),
					),
					'allorany' => 'all',
				),
			),
			array (
				'key' => 'field_55f3193b265cd',
				'label' => '지역',
				'name' => 'house_site',
				'type' => 'taxonomy',
				'required' => 1,
				'taxonomy' => 'site',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'object',
				'multiple' => 0,
			),
			array (
				'key' => 'field_55f319c698b4b',
				'label' => '이미지',
				'name' => 'house_images',
				'type' => 'image',
				'instructions' => '<ol>
	<li>여러 개의 이미지를 한 번에 업로드할 수 있습니다.</li>
	<li>업로드만 하면 해당 매물에 대한 이미지는 추가된 것입니다.</li>
	<li>업로드 후 프런트의 목록에 나타낼 대표 이미지 하나를 반드시 선택하고 \'선택\' 버튼을 클릭하세요.</li>
	<li>수정, 삭제의 경우 \'x\' 아이콘을 클릭한 후에 다시 \'연필\' 아이콘을 클릭하여 진행하세요.</li>
	<li>이미지는 <span style="color:red">jpg, jpeg, png</span> 형식만 가능합니다.</li>
	</ol>
	<p>이미지는 최소 <span style="color:red">"width: 750px; height: 356px"</span> 크기(또는 비율)로 맞춰서 등록하는 것이 좋습니다.</p>',
				'required' => 1,
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_55f31a74d982c',
				'label' => '위치',
				'name' => 'house_location',
				'type' => 'google_map',
				'instructions' => '<p>검색으로 위치를 지정하거나 지도에서 원하는 지역을 클릭하면 주소가 나타납니다. 지도를 확대하고 마우스로 마커를 이동하여 세부 위치를 지정할 수 있습니다.</p>
	<p>매물 위치에 따라 불가한 것도 있겠지만, 지도의 사람 아이콘을 매물 위치 근처로 드래그하여 \'스트리트 뷰\' 상태로 전환한 뒤 \'도로\'에서 매물이 보이도록 위치를 지정하는 것이 좋습니다.</p>',
				'required' => 1,
				'center_lat' => '37.586876',
				'center_lng' => '126.974790',
				'zoom' => 12,
				'height' => 400,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'house',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'slug',
			),
		),
		'menu_order' => 0,
	));
}
